---
- hosts: qemu
  gather_facts: false
  connection: local
  vars:
    vyos_platform: QEMU
    vyos_format: raw
    vyos_qemu_raw_img: "/tmp/vyos-{{ vyos_version }}{{ ci_tag  | default() }}-{{vyos_disk_size}}G-qemu.raw"
    vyos_output_img: "{{ vyos_qemu_img }}"
    cloud_init: "false"
    cloud_init_ds_string: "{{ cloud_init_ds | default('NoCloud,ConfigDrive,None') }}"
    cloud_init_ds_list: "{{ cloud_init_ds_string.split(',') }}"
  tasks:
    - block:
        - include_role:
            name: '{{ roleinputvar }}'
          loop:
            - install-packages
            - download-iso
            - mount-iso
            - get-version
            - create-disk
            - setup-root-partition
            - install-image
            - mount-root-fs
            - install-config
            - install-grub-wrapper
            - install-persistence-conf
            - install-cloud-init-wrapper
            - install-guest-agent-wrapper
            - fstrim
            - unmount-pre
            - create-pxe-archive
            - unmount-all
            - qemu-raw
            - cleanup-ending
            - release
          loop_control:
            loop_var: roleinputvar
      rescue:
        - include_role:
            name: '{{ roleinputvar }}'
          loop:
            - unmount-pre
            - unmount-all
          loop_control:
            loop_var: roleinputvar

