---
- hosts: vagrant_libvirt
  become: True
  gather_facts: False
  connection: local
  vars:
    vyos_platform: vagrant-libvirt
    vyos_format: box
    vyos_vagrant_libvirt_box: "vyos_vagrant_libvirt_image.box"
    vyos_output_img: "{{ vyos_vagrant_libvirt_box }}"
    cloud_init: False
    enable_dhcp: True
    enable_ssh: True
    vagrant_provider: libvirt
  roles:
    - install-packages
    - download-iso
    - mount-iso
    - get-version
    - create-disk
    - setup-root-partition
    - install-image
    - mount-root-fs
    - install-config
    - install-grub-wrapper
    - install-persistence-conf
    - unmount-pre
    - unmount-all
    - vagrant-libvirt-box
    - release-vagrant-box
